import "../globals.css";
import { Appbar, Footer } from '@/components'

export const metadata = {
  title: "Picknbuy",
  description: "Generated by create next app",
  openGraph: {
    title: "Picknbuy",
    description: "Find your next great deal!",
    images: [
      {
        url: '/Images/logo.png', 
        width: 800,
        height: 600,
        alt: "Picknbuy logo",
      },
    ],
    siteName: "Picknbuy",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="myfont flex flex-col min-h-screen" 
      >
        < Appbar />
        <main className="flex-grow max-w-screen-xl  w-full h-full mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
