import "../globals.css";
import { Appbar, Footer } from '@/components'
import { Providers } from "@/app/Redux/Provider";

export const metadata = {
  title: 'PicknBuy',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="myfont flex flex-col min-h-screen" 
      >
        <Providers>
        < Appbar />
        <main className="flex-grow max-w-screen-xl  w-full h-full mx-auto">
          {children}
        </main>
        <Footer />
        </Providers>
      </body>
    </html>
  )
}
