import "../globals.css";
import { Appbar, Footer } from '@/components'
import { Providers } from "@/app/Redux/Provider";

export const metadata = {
  title: 'UA Store',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section className="myfont flex flex-col min-h-screen max-h-full" >
        <Providers>
        < Appbar />
        <main className="flex-grow max-w-screen-xl w-full flex flex-col mx-auto">
          {children}
        </main>
        <Footer />
        </Providers>
        </section>
      </body>
    </html>
  )
}
