import localFont from "next/font/local";
import "./globals.css";
import { Appbar,Footer } from '@/components'
import logo from '@/components/Images/logo.png'
import { Providers } from "@/GlobalRedux/Provider";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Picknbuy",
  description: "Generated by create next app",
  openGraph: {
    title: "Picknbuy",
    description: "Find your next great deal!",
    images: [
      {
        url: '/Images/logo.png', 
        width: 800,
        height: 600,
        alt: "Picknbuy logo",
      },
    ],
    siteName: "Picknbuy",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Providers>
        <Appbar/>
        <main className="flex-grow max-w-screen-2xl  w-full h-full mx-auto">
        {children}
        </main>
        <Footer/>
        </Providers>
      </body>
    </html>
  );
}
