import './globals.css'
export const metadata = {
  title: 'Page Not Found',
  description: 'Generated by Next.js',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  )
}
